require('plugins.packer')
require('plugins.telescope')
require('plugins.barbar')
require('plugins.ntree')
require('plugins.lualine')
require('plugins.catppuccin')
require('plugins.syntaxis')
require('plugins.error')
